-- MySQL Script generated by MySQL Workbench
-- Tue 22 Jun 2021 02:17:51 PM -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

DROP DATABASE IF EXISTS mydb;
CREATE DATABASE mydb;
use mydb;

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `mydb`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Persona` (
  `DNI` INT NOT NULL,
  `Nombre` VARCHAR(64) NOT NULL,
  `Apellido` VARCHAR(64) NOT NULL,
  `Celular` VARCHAR(64) NULL,
  `Email` VARCHAR(64) NULL,
  PRIMARY KEY (`DNI`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Provincia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Provincia` (
  `ID_Provincia` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_Provincia`),
  UNIQUE INDEX `ID_Provincia_UNIQUE` (`ID_Provincia` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ciudad` (
	`ID_Ciudad` INT NOT NULL,
	`Nombre` VARCHAR(64) NOT NULL,
	`ID_Provincia` INT NOT NULL,
	PRIMARY KEY (`ID_Ciudad`),
	INDEX `ID_Provincia_idx` (`ID_Provincia` ASC) VISIBLE,
	FOREIGN KEY (`ID_Provincia`)
	REFERENCES `mydb`.`Provincia` (`ID_Provincia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Barrio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Barrio` (
	`ID_Barrio` INT NOT NULL,
	`Nombre` VARCHAR(64) NOT NULL,
	`ID_Ciudad` INT NOT NULL,
	PRIMARY KEY (`ID_Barrio`),
	INDEX `ID_Ciudad_idx` (`ID_Ciudad` ASC) VISIBLE,
	FOREIGN KEY (`ID_Ciudad`)
	REFERENCES `mydb`.`Ciudad` (`ID_Ciudad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Calle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Calle` (
	`ID_Calle` INT NOT NULL,
	`Nombre` VARCHAR(64) NOT NULL,
	`ID_Barrio` INT NOT NULL,
	PRIMARY KEY (`ID_Calle`),
	INDEX `ID_Barrio_idx` (`ID_Barrio` ASC) VISIBLE,
	FOREIGN KEY (`ID_Barrio`)
	REFERENCES `mydb`.`Barrio` (`ID_Barrio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estado_de_Inmueble`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estado_de_Inmueble` (
  `ID_Estado_de_Inmueble` INT NOT NULL,
  `Estado` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`ID_Estado_de_Inmueble`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Inmueble`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Inmueble` (
	`ID_Inmueble` INT NOT NULL,
	`Superficie` INT NOT NULL,
	`Antiguedad` INT NOT NULL,
	`Observaciones` LONGTEXT NULL,
	`ID_Calle` INT NOT NULL,
	`Altura` INT NOT NULL,
	`DNI_Propietario` INT NOT NULL,
	`ID_Estado` INT NOT NULL,
	PRIMARY KEY (`ID_Inmueble`),
	INDEX `ID_Propietario_idx` (`DNI_Propietario` ASC) VISIBLE,
	INDEX `ID_Calle_idx` (`ID_Calle` ASC) VISIBLE,
	INDEX `ID_Estado_idx` (`ID_Estado` ASC) VISIBLE,
	FOREIGN KEY (`DNI_Propietario`)
	REFERENCES `mydb`.`Persona` (`DNI`),
	FOREIGN KEY (`ID_Calle`)
	REFERENCES `mydb`.`Calle` (`ID_Calle`),
	FOREIGN KEY (`ID_Estado`)
	REFERENCES `mydb`.`Estado_de_Inmueble` (`ID_Estado_de_Inmueble`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Registro_de_Alquiler`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Registro_de_Alquiler` (
	`ID_Alquiler` INT NOT NULL,
	`ID_Inmueble` INT NOT NULL,
	`DNI_Inquilino` INT NOT NULL,
	`Encargado_de_Cuenta` INT NOT NULL,
	`Inicio_de_Contrato` DATE NOT NULL,
	`Fin_de_Contrato` DATE NOT NULL,
	PRIMARY KEY (`ID_Alquiler`),
	INDEX `DNI_Inquilino_idx` (`DNI_Inquilino` ASC) VISIBLE,
	INDEX `ID_Inmueble_idx` (`ID_Inmueble` ASC) VISIBLE,
	FOREIGN KEY (`DNI_Inquilino`)
	REFERENCES `mydb`.`Persona` (`DNI`),
	FOREIGN KEY (`ID_Inmueble`)
	REFERENCES `mydb`.`Inmueble` (`ID_Inmueble`),
	FOREIGN KEY (`Encargado_de_Cuenta`)
	REFERENCES `mydb`.`Personal` (`DNI`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Registro_de_Venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Registro_de_Venta` (
	`ID_Venta` INT NOT NULL,
	`ID_Inmueble` INT NOT NULL,
	`DNI_Cliente` INT NOT NULL,
	`Encargado_de_Cuenta` INT NOT NULL,
	`Fecha_de_Venta` DATE NOT NULL,
	PRIMARY KEY (`ID_Venta`),
	INDEX `DNI_Cliente` (`DNI_Cliente` ASC) VISIBLE,
	INDEX `ID_Inmueble_idx` (`ID_Inmueble` ASC) VISIBLE,
	FOREIGN KEY (`DNI_Cliente`)
	REFERENCES `mydb`.`Persona` (`DNI`),
	FOREIGN KEY (`ID_Inmueble`)
	REFERENCES `mydb`.`Inmueble` (`ID_Inmueble`),
	FOREIGN KEY (`Encargado_de_Cuenta`)
	REFERENCES `mydb`.`Personal` (`DNI`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Pago_de_Alquiler`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pago_de_Alquiler` (
	`ID_Pago_de_Alquiler` INT NOT NULL,
	`ID_Registro_de_Alquiler` INT NOT NULL,
	`Fecha_de_Pago` DATE NOT NULL,
	`Monto` INT NOT NULL,
	`Fecha_de_Emision` DATE NOT NULL,
	PRIMARY KEY (`ID_Pago_de_Alquiler`),
	INDEX `ID_Registro_de_Alquiler_idx` (`ID_Registro_de_Alquiler` ASC) VISIBLE,
	FOREIGN KEY (`ID_Registro_de_Alquiler`)
	REFERENCES `mydb`.`Registro_de_Alquiler` (`ID_Alquiler`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tipo_Operacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tipo_Operacion` (
  `ID_Tipo_Operacion` INT NOT NULL,
  `Tipo` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`ID_Tipo_Operacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Busqueda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Busqueda` (
	`ID_Busqueda` INT NOT NULL,
	`DNI_Consultante` INT NOT NULL,
	`ID_Operacion` INT NOT NULL,
	`Fecha` DATE NOT NULL,
	`Hora` TIME NOT NULL,
	`Monto_Minimo` INT NOT NULL,
	`Monto_Maximo` INT NOT NULL,
	PRIMARY KEY (`ID_Busqueda`),
	INDEX `DNI_Consultante_idx` (`DNI_Consultante` ASC) VISIBLE,
	INDEX `ID_Operacion_idx` (`ID_Operacion` ASC) VISIBLE,
	FOREIGN KEY (`DNI_Consultante`)
	REFERENCES `mydb`.`Persona` (`DNI`),
	FOREIGN KEY (`ID_Operacion`)
	REFERENCES `mydb`.`Tipo_Operacion` (`ID_Tipo_Operacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Oferta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Oferta` (
	`ID_Oferta` INT NOT NULL,
	`ID_Tipo_Operacion` INT NOT NULL,
	`Encargado_de_Cuenta` INT NOT NULL,
	`ID_Inmueble` INT NOT NULL,
	`Fecha_de_Inicio` DATE NOT NULL,
	`Monto` INT NOT NULL,
	`Validez_de_Pago` DATE NOT NULL,
	PRIMARY KEY (`ID_Oferta`),
	INDEX `ID_Inmueble_idx` (`ID_Inmueble` ASC) VISIBLE,
	INDEX `Encargado_de_Cuenta_idx` (`Encargado_de_Cuenta` ASC) VISIBLE,
	INDEX `ID_Tipo_Operacion_idx` (`ID_Tipo_Operacion` ASC) VISIBLE,
	FOREIGN KEY (`ID_Inmueble`)
    REFERENCES `mydb`.`Inmueble` (`ID_Inmueble`),
    FOREIGN KEY (`Encargado_de_Cuenta`)
    REFERENCES `mydb`.`Personal` (`DNI`),
    FOREIGN KEY (`ID_Tipo_Operacion`)
    REFERENCES `mydb`.`Tipo_Operacion` (`ID_Tipo_Operacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Registro_de_Busqueda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Registro_de_Busqueda` (
	`ID_Busqueda` INT NOT NULL,
	`ID_Oferta` INT NOT NULL,
	PRIMARY KEY (`ID_Busqueda`),
	INDEX `ID_Oferta_idx` (`ID_Oferta` ASC) VISIBLE,
	FOREIGN KEY (`ID_Busqueda`)
	REFERENCES `mydb`.`Busqueda` (`ID_Busqueda`),
	FOREIGN KEY (`ID_Oferta`)
	REFERENCES `mydb`.`Oferta` (`ID_Oferta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tipo_de_Caracteristica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tipo_de_Caracteristica` (
  `ID_Tipo_de_Caracteristica` INT NOT NULL,
  `Tipo` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`ID_Tipo_de_Caracteristica`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Caracteristicas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Caracteristicas` (
	`ID_Caracteristica` INT NOT NULL,
	`ID_Inmueble` INT NOT NULL,
	`ID_Tipo` INT NOT NULL,
	`Cantidad` INT NOT NULL,
	PRIMARY KEY (`ID_Caracteristica`),
	INDEX `ID_Inmueble_idx` (`ID_Inmueble` ASC) VISIBLE,
	INDEX `ID_Tipo_idx` (`ID_Tipo` ASC) VISIBLE,
	FOREIGN KEY (`ID_Inmueble`)
	REFERENCES `mydb`.`Inmueble` (`ID_Inmueble`),
	FOREIGN KEY (`ID_Tipo`)
	REFERENCES `mydb`.`Tipo_de_Caracteristica` (`ID_Tipo_de_Caracteristica`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tipo_de_Mejora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tipo_de_Mejora` (
  `ID_Tipo_de_Mejora` INT NOT NULL,
  `Tipo` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`ID_Tipo_de_Mejora`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mejoras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mejoras` (
	`ID_Mejora` INT NOT NULL,
	`Fecha` DATE NOT NULL,
	`Superficie` INT NOT NULL,
	`Descripcion` VARCHAR(128) NOT NULL,
	`ID_Tipo` INT NOT NULL,
	`ID_Inmueble` INT NOT NULL,
	PRIMARY KEY (`ID_Mejora`),
	INDEX `ID_Inmueble_idx` (`ID_Inmueble` ASC) VISIBLE,
	INDEX `ID_Tipo_idx` (`ID_Tipo` ASC) VISIBLE,
	FOREIGN KEY (`ID_Inmueble`)
	REFERENCES `mydb`.`Inmueble` (`ID_Inmueble`),
	FOREIGN KEY (`ID_Tipo`)
	REFERENCES `mydb`.`Tipo_de_Mejora` (`ID_Tipo_de_Mejora`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comodidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Comodidad` (
	`ID_Comodidad` INT NOT NULL,
	`ID_Busqueda` INT NOT NULL,
	`ID_Tipo` INT NOT NULL,
	`Cantidad` INT NOT NULL,
	PRIMARY KEY (`ID_Comodidad`),
	INDEX `ID_Busqueda_idx` (`ID_Busqueda` ASC) VISIBLE,
	INDEX `ID_Tipo_idx` (`ID_Tipo` ASC) VISIBLE,
	FOREIGN KEY (`ID_Busqueda`)
	REFERENCES `mydb`.`Busqueda` (`ID_Busqueda`),
	FOREIGN KEY (`ID_Tipo`)
	REFERENCES `mydb`.`Tipo_de_Caracteristica` (`ID_Tipo_de_Caracteristica`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pago_de_Impuestos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pago_de_Impuestos` (
	`ID_Pago_de_Impuestos` INT NOT NULL,
	`ID_Registro_de_Alquiler` INT NOT NULL,
	`Fecha_de_Pago` DATE NOT NULL,
	`Monto` INT NOT NULL,
	`Fecha_de_Emision` DATE NOT NULL,
	PRIMARY KEY (`ID_Pago_de_Impuestos`),
	INDEX `ID_Registro_de_Alquiler_idx` (`ID_Registro_de_Alquiler` ASC) VISIBLE,
	FOREIGN KEY (`ID_Registro_de_Alquiler`)
	REFERENCES `mydb`.`Registro_de_Alquiler` (`ID_Alquiler`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`Personal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Personal` (
  `DNI` INT NOT NULL,
  `Nombre` VARCHAR(64) NOT NULL,
  `Apellido` VARCHAR(64) NOT NULL,
  `Celular` VARCHAR(64) NULL,
  `Email` VARCHAR(64) NULL,
  PRIMARY KEY (`DNI`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
